export const orders = [
  {
    id: '6c84fb90-12c4-11e1-840d-7b25c5ee775a',
    number: 1,
    patientName: 'William Smith',
    physicianName: 'Dr. John Doe',
    dueDate: '2023-10-22T09:00:00',
    read: true,
    labels: ['pre-surgery'],
    hospitalName: 'Hospital A',
    insuranceCompanyName: 'Amil',
    internalSpecialistName: '',
    items: [],
    total: 150000,
  },
  {
    id: '110e8400-e29b-11d4-a716-446655440000',
    number: 2,
    patientName: 'Alice Smith',
    physicianName: 'Dr. Jane Doe',
    dueDate: '2023-10-22T10:30:00',
    read: true,
    labels: ['post-surgery'],
    hospitalName: 'Hospital B',
    insuranceCompanyName: 'SulAmerica',
    internalSpecialistName: '',
    items: [],
    total: 180000,
  },
  {
    id: '3e7c3f6d-bdf5-46ae-8d90-171300f27ae2',
    number: 3,
    patientName: 'Bob Johnson',
    physicianName: 'Dr. Emily Clark',
    dueDate: '2023-04-10T11:45:00',
    read: true,
    labels: ['pre-surgery'],
    hospitalName: 'Hospital C',
    insuranceCompanyName: 'Unimed',
    internalSpecialistName: '',
    items: [],
    total: 120000,
  },
  {
    id: '61c35085-72d7-42b4-8d62-738f700d4b92',
    number: 4,
    patientName: 'Emily Davis',
    physicianName: 'Dr. Michael Brown',
    dueDate: '2023-03-25T13:15:00',
    read: false,
    labels: ['post-surgery'],
    hospitalName: 'Hospital D',
    insuranceCompanyName: 'PreventSenior',
    internalSpecialistName: '',
    items: [],
    total: 190000,
  },
  {
    id: '8f7b5db9-d935-4e42-8e05-1f1d0a3dfb97',
    number: 5,
    patientName: 'Michael Wilson',
    physicianName: 'Dr. Lisa White',
    dueDate: '2023-03-10T15:00:00',
    read: false,
    labels: ['pre-surgery'],
    hospitalName: 'Hospital E',
    insuranceCompanyName: 'Omint',
    internalSpecialistName: '',
    items: [],
    total: 110000,
  },
  {
    id: '1f0f2c02-e299-40de-9b1d-86ef9e42126b',
    number: 6,
    patientName: 'Sarah Brown',
    physicianName: 'Dr. David Harris',
    dueDate: '2023-02-15T16:30:00',
    read: true,
    labels: ['post-surgery'],
    hospitalName: 'Hospital F',
    insuranceCompanyName: 'Bradesco',
    internalSpecialistName: '',
    items: [],
    total: 140000,
  },
  {
    id: '17c0a96d-4415-42b1-8b4f-764efab57f66',
    number: 7,
    patientName: 'David Lee',
    physicianName: 'Dr. Laura Martinez',
    dueDate: '2023-01-28T17:45:00',
    read: false,
    labels: ['pre-surgery'],
    hospitalName: 'Hospital G',
    insuranceCompanyName: 'Amil',
    internalSpecialistName: '',
    items: [],
    total: 130000,
  },
  {
    id: '2f0130cb-39fc-44c4-bb3c-0a4337edaaab',
    number: 8,
    patientName: 'Olivia Wilson',
    physicianName: 'Dr. Peter Johnson',
    dueDate: '2022-12-20T18:30:00',
    read: true,
    labels: ['post-surgery'],
    hospitalName: 'Hospital H',
    insuranceCompanyName: 'SulAmerica',
    internalSpecialistName: '',
    items: [],
    total: 160000,
  },
  {
    id: 'de305d54-75b4-431b-adb2-eb6b9e546014',
    number: 9,
    patientName: 'James Martin',
    physicianName: 'Dr. Robert Miller',
    dueDate: '2022-11-30T19:15:00',
    read: true,
    labels: ['pre-surgery'],
    hospitalName: 'Hospital I',
    insuranceCompanyName: 'Unimed',
    internalSpecialistName: '',
    items: [],
    total: 125000,
  },
  {
    id: '7dd90c63-00f6-40f3-bd87-5060a24e8ee7',
    number: 10,
    patientName: 'Sophia White',
    physicianName: 'Dr. Karen Wilson',
    dueDate: '2022-11-05T20:30:00',
    read: false,
    labels: ['post-surgery'],
    hospitalName: 'Hospital J',
    insuranceCompanyName: 'PreventSenior',
    internalSpecialistName: '',
    items: [],
    total: 175000,
  },
  {
    id: '99a88f78-3eb4-4d87-87b7-7b15a49a0a05',
    number: 11,
    patientName: 'Daniel Johnson',
    physicianName: 'Dr. Nancy Davis',
    dueDate: '2022-10-22T09:30:00',
    read: false,
    labels: ['pre-surgery'],
    hospitalName: 'Hospital K',
    insuranceCompanyName: 'Omint',
    internalSpecialistName: '',
    items: [],
    total: 105000,
  },
  {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    number: 12,
    patientName: 'Ava Taylor',
    physicianName: 'Dr. Charles Clark',
    dueDate: '2022-10-10T10:45:00',
    read: true,
    labels: ['post-surgery'],
    hospitalName: 'Hospital L',
    insuranceCompanyName: 'Bradesco',
    internalSpecialistName: '',
    items: [],
    total: 145000,
  },
  {
    id: 'c1a0ecb4-2540-49c5-86f8-21e5ce79e4e6',
    number: 13,
    patientName: 'William Anderson',
    physicianName: 'Dr. Emma Thompson',
    dueDate: '2022-09-20T12:00:00',
    read: false,
    labels: ['pre-surgery'],
    hospitalName: 'Hospital M',
    insuranceCompanyName: 'Amil',
    internalSpecialistName: '',
    items: [],
    total: 170000,
  },
  {
    id: 'ba54eefd-4097-4949-99f2-2a9ae4d1a836',
    number: 14,
    patientName: 'Mia Harris',
    physicianName: 'Dr. Andrew Lee',
    dueDate: '2022-09-10T13:15:00',
    read: true,
    labels: ['post-surgery'],
    hospitalName: 'Hospital N',
    insuranceCompanyName: 'SulAmerica',
    internalSpecialistName: '',
    items: [],
    total: 115000,
  },
  {
    id: 'df09b6ed-28bd-4e0c-85a9-9320ec5179aa',
    number: 15,
    patientName: 'Ethan Clark',
    physicianName: 'Dr. Maria Lopez',
    dueDate: '2022-08-25T15:30:00',
    read: false,
    labels: ['pre-surgery'],
    hospitalName: 'Hospital O',
    insuranceCompanyName: 'Unimed',
    internalSpecialistName: '',
    items: [],
    total: 135000,
  },
  {
    id: 'd67c1842-7f8b-4b4b-9be1-1b3b1ab4611d',
    number: 16,
    patientName: 'Chloe Hall',
    physicianName: 'Dr. Paul Walker',
    dueDate: '2022-08-10T16:45:00',
    read: true,
    labels: ['post-surgery'],
    hospitalName: 'Hospital P',
    insuranceCompanyName: 'PreventSenior',
    internalSpecialistName: '',
    items: [],
    total: 185000,
  },
  {
    id: '6c9a7f94-8329-4d70-95d3-51f68c186ae1',
    number: 17,
    patientName: 'Samuel Turner',
    physicianName: 'Dr. Jessica Hall',
    dueDate: '2022-07-28T17:30:00',
    read: false,
    labels: ['pre-surgery'],
    hospitalName: 'Hospital Q',
    insuranceCompanyName: 'Omint',
    internalSpecialistName: '',
    items: [],
    total: 155000,
  },
];

export const contacts = [
  {
    name: 'Emma Johnson',
    email: 'emma.johnson@example.com',
  },
  {
    name: 'Liam Wilson',
    email: 'liam.wilson@example.com',
  },
  {
    name: 'Olivia Davis',
    email: 'olivia.davis@example.com',
  },
  {
    name: 'Noah Martinez',
    email: 'noah.martinez@example.com',
  },
  {
    name: 'Ava Taylor',
    email: 'ava.taylor@example.com',
  },
  {
    name: 'Lucas Brown',
    email: 'lucas.brown@example.com',
  },
  {
    name: 'Sophia Smith',
    email: 'sophia.smith@example.com',
  },
  {
    name: 'Ethan Wilson',
    email: 'ethan.wilson@example.com',
  },
  {
    name: 'Isabella Jackson',
    email: 'isabella.jackson@example.com',
  },
  {
    name: 'Mia Clark',
    email: 'mia.clark@example.com',
  },
  {
    name: 'Mason Lee',
    email: 'mason.lee@example.com',
  },
  {
    name: 'Layla Harris',
    email: 'layla.harris@example.com',
  },
  {
    name: 'William Anderson',
    email: 'william.anderson@example.com',
  },
  {
    name: 'Ella White',
    email: 'ella.white@example.com',
  },
  {
    name: 'James Thomas',
    email: 'james.thomas@example.com',
  },
  {
    name: 'Harper Lewis',
    email: 'harper.lewis@example.com',
  },
  {
    name: 'Benjamin Moore',
    email: 'benjamin.moore@example.com',
  },
  {
    name: 'Aria Hall',
    email: 'aria.hall@example.com',
  },
  {
    name: 'Henry Turner',
    email: 'henry.turner@example.com',
  },
  {
    name: 'Scarlett Adams',
    email: 'scarlett.adams@example.com',
  },
];
